### ISSUE TITLE
Update policy doc creation concerning AbstractMappedPolicy

### ISSUE THREAD

**Issue by cmoulliard** [apiman/apiman-guides#13]
The developer doc guide to create a Policy explains that we have to implement the IPolicy interface while the concrete examples extends the class `extends AbstractMappedPolicy<T>`. The doc includes a WARN message which is placed far away in the doc. We could update that

**Comment by EricWittmann** [comment]
Moved here: https://issues.jboss.org/browse/APIMAN-930
